; This file for the FamiStudio Sound Engine and was generated by FamiStudiomusic_data_song_2

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_song_2=music_data_song_2
.endif

music_data_song_2:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 2
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_song_2
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $ff, $87, $47, $ff, $ff, $ff, $87, $47, $ff, $ff
	.byte $ff, $87, $47, $ff, $ff, $ff, $87, $47, $80
@song0ref26:
	.byte $19, $97, $1e, $95, $20, $95, $19, $95, $23, $97, $19, $95, $1e, $95, $20, $95, $19, $97, $23, $95, $19, $95, $1e, $95
	.byte $20, $97, $19, $95, $23, $95, $19, $95, $47
	.byte $41, $1a
	.word @song0ref26
	.byte $1e, $95, $19, $95, $00, $95
@song0ref68:
	.byte $47, $ff, $ff, $ff, $87, $47, $ff, $ff, $ff, $87, $47, $ff, $ff, $ff, $87, $47, $ff, $ff, $ff, $87, $47, $ff, $ff, $ff
	.byte $87
	.byte $41, $14
	.word @song0ref68
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $80
@song0ref109:
	.byte $06, $97, $12, $95, $06, $95, $12, $95, $08, $97, $14, $95, $08, $95, $14
@song0ref124:
	.byte $95, $03, $97, $0f, $95, $03, $95, $0f, $95, $03, $97, $0f, $95, $03, $95, $0f, $95, $01, $97, $0d, $95, $01, $95, $0d
	.byte $95, $06, $97, $12, $95, $06, $95, $12
	.byte $41, $11
	.word @song0ref124
	.byte $41, $2f
	.word @song0ref109
	.byte $41, $11
	.word @song0ref124
@song0ref165:
	.byte $00, $ff, $ff, $ff, $85
@song0ref170:
	.byte $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $ff, $ff, $ff, $87
	.byte $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $ff, $ff, $ff, $87, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref211:
	.byte $16, $97, $16, $95, $16, $95, $16, $95, $17, $97, $17, $95, $17, $95, $17, $95, $0f, $97, $0f, $95, $0f, $95, $0f, $95
	.byte $0f, $97, $0f, $95, $0f, $95, $0f, $95
	.byte $41, $20
	.word @song0ref211
	.byte $41, $20
	.word @song0ref211
@song0ref249:
	.byte $12, $97, $12, $95, $12, $95, $12, $95, $12, $97, $12, $95, $12, $95, $12, $95, $14, $97, $14, $95, $14, $95, $14, $95
	.byte $14, $97, $14, $95, $14, $95, $14, $95
	.byte $41, $20
	.word @song0ref211
	.byte $41, $20
	.word @song0ref249
	.byte $41, $29
	.word @song0ref165
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref295:
	.byte $14, $8b, $00, $89, $23, $89, $00, $89, $23, $89, $00, $89, $23, $89, $00, $89, $17, $8b, $00, $89, $23, $89, $00, $89
	.byte $23, $89, $00, $89, $23, $89, $00, $89
	.byte $41, $20
	.word @song0ref295
	.byte $41, $20
	.word @song0ref295
	.byte $41, $18
	.word @song0ref295
	.byte $17, $89, $00, $89, $17, $89, $00, $89
	.byte $41, $20
	.word @song0ref295
	.byte $41, $18
	.word @song0ref295
	.byte $17, $89, $00, $89, $23, $89, $00, $89
	.byte $41, $20
	.word @song0ref295
	.byte $41, $18
	.word @song0ref295
	.byte $17, $89, $00, $89, $17, $95
	.byte $41, $20
	.word @song0ref295
	.byte $41, $18
	.word @song0ref295
	.byte $17, $89, $00, $89, $23, $89, $00, $89
	.byte $41, $20
	.word @song0ref295
	.byte $41, $18
	.word @song0ref295
	.byte $17, $89, $00, $89, $17, $95, $8d, $00, $ff, $ff, $f7
	.byte $41, $24
	.word @song0ref170
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $24
	.word @song0ref170
	.byte $41, $1c
	.word @song0ref170
	.byte $42
	.word @song0ch4loop
