; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_song_1=music_data_song_1
.endif

music_data_song_1:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_song_1
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $ef, $47, $ff, $ff, $ef, $47, $80
@song0ref14:
	.byte $19, $95, $19, $93, $21, $95, $19, $93, $20, $95, $19, $93, $1e, $95, $19, $93, $1c, $95, $19, $93, $1e, $95, $19, $93
	.byte $1c, $95, $19, $93, $17, $95, $19, $93, $47, $21, $95, $19, $93, $20, $95, $19, $93, $1e, $95, $19, $93, $1c, $95, $19
	.byte $93, $15, $95, $19, $93, $1c, $95, $19, $93, $15, $95, $19, $93, $14, $95, $19, $93, $47
	.byte $41, $40
	.word @song0ref14
	.byte $47
	.byte $41, $40
	.word @song0ref14
	.byte $47
	.byte $41, $40
	.word @song0ref14
@song0ref91:
	.byte $47, $0d, $95, $0d, $93, $0d, $95, $0f, $93, $0f, $95, $0f, $93, $10, $95, $10, $93, $10, $95, $12, $93, $12, $95, $12
	.byte $93, $14, $95, $14, $93, $14, $95, $15, $93
	.byte $41, $20
	.word @song0ref91
	.byte $41, $20
	.word @song0ref91
	.byte $41, $20
	.word @song0ref91
	.byte $41, $20
	.word @song0ref91
	.byte $41, $20
	.word @song0ref91
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref144:
	.byte $15, $95, $15, $93, $15, $95, $15, $93, $14, $95, $14, $93, $14, $95, $14, $93, $12, $95, $12, $93, $12, $95, $14, $93
	.byte $10, $95, $10, $93, $10, $95, $10, $93, $0b, $95, $0b, $93, $0b, $95, $12, $93, $12, $95, $12, $93, $10, $95, $10, $93
	.byte $10, $95, $0f, $93, $0f, $95, $0f, $93, $17, $95, $17, $93, $17, $95, $17, $93
	.byte $41, $40
	.word @song0ref144
	.byte $41, $40
	.word @song0ref144
@song0ref214:
	.byte $10, $95, $10, $93, $1c, $95, $10, $93, $10, $95, $10, $93, $1c, $95, $10, $93, $08, $95, $08, $93, $14, $95, $08, $93
	.byte $08, $95, $08, $93, $14, $95, $08, $93, $09, $95, $09, $93, $15, $95, $09, $93, $09, $95, $09, $93, $15, $95, $09, $93
	.byte $0b, $95, $0b, $93, $17, $95, $0b, $93, $0b, $95, $0b, $93, $17, $95, $01, $93
	.byte $41, $40
	.word @song0ref214
@song0ref281:
	.byte $01, $95, $01, $93, $01, $95, $01, $93, $01, $95, $01, $93, $01, $95, $01, $93, $01, $95, $01, $93, $01, $95, $01, $93
	.byte $01, $95, $01, $93, $01, $95, $01, $93, $09, $95, $09, $93, $09, $95, $09, $93, $09, $95, $09, $93, $09, $95, $09, $93
	.byte $09, $95, $09, $93, $09, $95, $09, $93, $09, $95, $09, $93, $09, $95, $09, $93, $04, $95, $04, $93, $04, $95, $04, $93
	.byte $04, $95, $04, $93, $04, $95, $04, $93, $04, $95, $04, $93, $04, $95, $04, $93, $04, $95, $04, $93, $04, $95, $04, $93
	.byte $41, $60
	.word @song0ref281
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref385:
	.byte $0d, $95, $19, $93, $19, $95, $0d, $93, $19, $95, $19, $93, $0d, $95, $19, $93, $19, $95, $0f, $93, $1b, $95, $1b, $93
	.byte $10, $95, $1c, $93, $1c, $95, $10, $93, $1c, $95, $1c, $93, $0b, $95, $17, $93, $17, $95, $0b, $93, $17, $95, $17, $93
	.byte $09, $95, $15, $93, $15, $95, $09, $93, $15, $95, $15, $93, $09, $95, $0d, $93
	.byte $41, $40
	.word @song0ref385
	.byte $41, $40
	.word @song0ref385
@song0ref455:
	.byte $1c, $95, $1c, $93, $1c, $95, $1c, $93, $1c, $95, $1c, $93, $1c, $95, $1c, $93, $14, $95, $14, $93, $14, $95, $14, $93
	.byte $14, $95, $14, $93, $14, $95, $14, $93, $15, $95, $15, $93, $15, $95, $15, $93, $15, $95, $15, $93, $15, $95, $15, $93
	.byte $17, $95, $17, $93, $17, $95, $17, $93, $17, $95, $17, $93, $19, $95, $19, $93
	.byte $41, $40
	.word @song0ref455
	.byte $00, $ff, $ff, $ed, $ff, $ff, $ef, $ff, $ff, $ef
@song0ref532:
	.byte $28, $95, $19, $93, $27, $95, $19, $93, $25, $95, $19, $93, $1e, $95, $20, $93, $28, $95, $19, $93, $27, $95, $19, $93
	.byte $25, $95, $19, $93, $1e, $95, $20, $93
	.byte $41, $20
	.word @song0ref532
	.byte $41, $20
	.word @song0ref532
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref575:
	.byte $05, $81, $00, $91, $13, $81, $00, $8f, $05, $81, $00, $91, $13, $81, $00, $8f, $09, $81, $00, $91, $13, $81, $00, $8f
	.byte $05, $81, $00, $91, $13, $81, $00, $8f, $05, $81, $00, $91, $13, $81, $00, $8f, $05, $81, $00, $91, $13, $81, $00, $8f
	.byte $09, $81, $00, $91, $13, $81, $00, $8f, $09, $81, $00, $91, $13, $81, $00, $8f
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $40
	.word @song0ref575
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $40
	.word @song0ref575
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $40
	.word @song0ref575
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $40
	.word @song0ref575
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $40
	.word @song0ref575
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $40
	.word @song0ref575
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00
	.byte $41, $3c
	.word @song0ref575
	.byte $09, $89, $00, $07, $83, $00, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef
	.byte $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef, $ff, $ff, $ef
	.byte $42
	.word @song0ch4loop
