; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_titlescreen=music_data_titlescreen
.endif

music_data_titlescreen:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : titlescreen
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_titlescreen
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1
	.word @env1,@env2,@env3,@env0 ; 01 : Instrument 2

@samples:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $82
@song0ref6:
	.byte $4f, $27, $14, $0f, $a5, $0f, $a5, $00, $b9, $4f, $04, $51, $4a, $91, $3d, $91, $3e, $91, $40, $4f, $91, $40, $4d, $91
	.byte $3d, $91, $00, $b9, $47
	.byte $41, $14
	.word @song0ref6
	.byte $47
	.byte $41, $14
	.word @song0ref6
	.byte $47
	.byte $41, $14
	.word @song0ref6
	.byte $47
	.byte $41, $14
	.word @song0ref6
	.byte $47
	.byte $41, $14
	.word @song0ref6
	.byte $47
	.byte $41, $14
	.word @song0ref6
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf
	.byte $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref99:
	.byte $14, $97, $00, $8b, $1b, $97, $00, $b3, $4f, $f4, $24, $27, $97, $1b, $89, $00, $cf, $4f, $ec, $25, $28, $8b, $00, $97
	.byte $1e, $8b, $00, $89, $1c, $89, $00
	.byte $41, $19
	.word @song0ref99
	.byte $41, $19
	.word @song0ref99
	.byte $41, $19
	.word @song0ref99
	.byte $41, $19
	.word @song0ref99
	.byte $41, $19
	.word @song0ref99
	.byte $41, $19
	.word @song0ref99
@song0ref148:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref180:
	.byte $08, $91, $00, $97, $08, $85, $00, $83, $08, $91, $00, $b1, $4f, $87, $14, $17, $83, $00, $0c, $91, $00, $a7, $0c, $83
	.byte $00, $81, $0c, $00, $83, $0d, $9f, $00, $bf
	.byte $41, $1e
	.word @song0ref180
	.byte $41, $1e
	.word @song0ref180
	.byte $41, $1e
	.word @song0ref180
	.byte $41, $1e
	.word @song0ref180
	.byte $41, $1e
	.word @song0ref180
	.byte $41, $1e
	.word @song0ref180
	.byte $41, $1b
	.word @song0ref148
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref239:
	.byte $14, $83, $00, $8b, $14, $83, $00, $8b, $1a, $83, $00, $b3, $14, $81, $00, $81, $14, $81, $00, $85, $1a, $81, $00, $a1
	.byte $14, $85, $00, $9d, $1a, $87, $00, $b1, $14, $83, $00, $89, $1b, $83, $00, $9f
	.byte $41, $28
	.word @song0ref239
	.byte $41, $28
	.word @song0ref239
	.byte $41, $28
	.word @song0ref239
	.byte $41, $28
	.word @song0ref239
	.byte $41, $28
	.word @song0ref239
	.byte $41, $28
	.word @song0ref239
	.byte $41, $1b
	.word @song0ref148
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $1b
	.word @song0ref148
	.byte $41, $15
	.word @song0ref148
	.byte $42
	.word @song0ch4loop
